### PR TITLE
Replace static MPPWCC page with yearly & add previous year's info

### PR DESCRIPTION
**Pull request by jwade1327**
Screen Shot 2022-03-24 at 2 04 22 PM
Screen Shot 2022-03-24 at 2 04 31 PM
Screen Shot 2022-03-24 at 2 04 37 PM
Screen Shot 2022-03-24 at 2 04 44 PM
Screen Shot 2022-03-24 at 2 04 51 PM
Screen Shot 2022-03-24 at 2 04 58 PM
Screen Shot 2022-03-24 at 2 05 05 PM

### CODE REVIEW

**Comment by jwade1327** [comment]
[2015 MPPTW in CC](https://trello.com/c/eTAmKHw9/198-2015-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2016 MPPTW in CC](https://trello.com/c/g3jzJUdQ/197-2016-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2017 MPPTW in CC](https://trello.com/c/Ppq4qvIx/196-2017-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2018 MPPTW in CC](https://trello.com/c/0nWJ5ZmW/194-2018-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2019 MPPTW in CC](https://trello.com/c/Hp1oWrFR/193-2019-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2020 MPPTW in CC](https://trello.com/c/QCI2jZSt/192-2020-mpptw-in-cc)

**Comment by jwade1327** [comment]
[2021 MPPTW in CC](https://trello.com/c/mz1dCfGN/190-2021-mpptw-in-cc)

**Review by Shinsina — APPROVED** [review]

**Pull request merged**
