### PR TITLE
Separate out 'MPPWSA-Yearly' into individual config files by year

### PR DESCRIPTION
**Pull request by jwade1327**
2014:
Screen Shot 2022-03-21 at 3 12 34 PM
2015:
Screen Shot 2022-03-21 at 1 15 48 PM
2016:
Screen Shot 2022-03-21 at 12 14 43 PM
2017:
Screen Shot 2022-03-21 at 10 14 58 AM

### CODE REVIEW

**Comment by jwade1327** [comment]
[2014 MPPWSA](https://trello.com/c/Wvb3J9q4/186-2014-mppwsa)

**Comment by jwade1327** [comment]
[2015 MPPWSA](https://trello.com/c/daKhgJjn/185-2015-mppwsa)

**Comment by jwade1327** [comment]
[2016 MPPWSA](https://trello.com/c/E2CKTJZr/184-2016-mppwsa)

**Comment by jwade1327** [comment]
[2017 MPPWSA](https://trello.com/c/e4VS3Axe/183-2017-mppwsa)

**Review by Shinsina — APPROVED** [review]

**Pull request merged**
